name: i_Sonno_Beta
description: Demonstrates how to use the alarm plugin.
version: 0.1.2

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  alarm: ^5.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  intl: any
  logging: ^1.3.0
  pedometer: ^4.1.1
  permission_handler: ^11.4.0
  sensors_plus: ^6.1.1
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3
    - assets/white_lady.mp3
    - assets/icons/shake.svg
    - assets/icons/xAxis.png
    - assets/icons/yAxis.png
    - assets/icons/zAxis.png
    - assets/icons/icon1.svg
    - assets/icons/icon2.svg
    - assets/icons/icon3.svg
    - assets/icons/ic_launcher_foreground.webp
